### PR TITLE
Upgrade to latest from dev

### PR DESCRIPTION
**Pull request by jnewland**
Deploying this as a branch for a bit to observe memory usage after https://github.com/jnewland/ha-config/issues/3.

### CODE REVIEW

**Comment by jnewland** [comment]
image

https://github.com/home-assistant/home-assistant/issues/6165 is tracking this issue upstream. I'll have some time to dig into this more later today.

**Comment by jnewland** [comment]
Two new differences from 383b0914b38449d7146f8027bd4b175a6941975f:

* Reverted https://github.com/home-assistant/home-assistant/pull/6100 so I can bring it in on my own terms
* https://github.com/home-assistant/netdisco/pull/99

**Comment by jnewland** [comment]
Still leaky.

**Comment by balloob** [comment]
Still leaky?🚰 

Could you try reverting https://github.com/home-assistant/netdisco/pull/94 if you are running custom netdisco ? (since you applied 99)

**Comment by jnewland** [comment]
> Still leaky?🚰

Heh I wondered if anyone would find this. I'm happy to test stuff out anytime. 💞

Things are looking good with https://github.com/home-assistant/home-assistant/pull/6321 merged in. I'll drop a comment on https://github.com/home-assistant/home-assistant/issues/6165 in a second.

**Pull request merged**
